<a href="https://colab.research.google.com/github/robinkm0610/DSA/blob/main/DSA/04_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from array import *

Create an array

In [14]:
arr1 = array('i', [1,2,3,4,5])
print(arr1)

array('i', [1, 2, 3, 4, 5])


In [15]:
arr2 = array('d', [1.2,2.3,3.4,4.5])
print(arr2)

array('d', [1.2, 2.3, 3.4, 4.5])


Insertion operation in array

In [4]:
arr1.insert(0,0)
print(arr1)

array('i', [0, 1, 2, 3, 4, 5])


In [5]:
arr1.append(6)
print(arr1)

array('i', [0, 1, 2, 3, 4, 5, 6])


Array traversal

In [6]:
def traverseArray(array):
  for i in array:
    print(i)
traverseArray(arr1)

0
1
2
3
4
5
6


Accessing an element in array

In [7]:
def accessElement(array, index):
  if index >= len(array):
    print("There is not any element in this index")
  else:
    print(array[index])
accessElement(arr1, 2)

2


Finding an element

In [8]:
def searchInArray(array,value):
  for i in array:
    if i == value:
      return array.index(value)
  return "The element does not exist in this array"
searchInArray(arr1, 3)

3

In [9]:
searchInArray(arr1, 10)

'The element does not exist in this array'

Deleting an element from array

In [16]:
print(arr1)
arr1.remove(2) #passing the actual element value
print(arr1)

array('i', [1, 2, 3, 4, 5])
array('i', [1, 3, 4, 5])


In [17]:
print(arr1)
arr1.remove(2)
print(arr1)

array('i', [1, 3, 4, 5])


ValueError: array.remove(x): x not in array

TIme and Space Complexity in One Dimensional Arrays

| Operation | Time Complexity | Space Complexity |
| --- | --- | --- |
| Creating an empty array | O(1) | O(n) |
| Inserting a value in an array | O(1)/O(n) | O(1) |
| Traversing a given array | O(n) | O(1) |
| Accessing a given cell | O(1) | O(1) |
| Searching a given value | O(n) | O(1) |
| Deleting a given value | O(1)/O(n) | O(1) |

In [27]:
# 1. Create an array and traverse.

from array import *

my_array = array('i', [1,2,3,4,5])

for i in my_array:
  print(i)

1
2
3
4
5


In [28]:
# 2. Access individual elements through indexes

print(my_array[2])

3


In [29]:
# 3. Append any value to the array using append() method

my_array.append(6)
print(my_array)

array('i', [1, 2, 3, 4, 5, 6])


In [30]:
# 4. Insert value in any array using insert() method

my_array.insert(0,11)
print(my_array)

array('i', [11, 1, 2, 3, 4, 5, 6])


In [31]:
# 5. Extend python array  using extend() method

my_array1 = array('i', [10,11,12])
my_array.extend(my_array1)
print(my_array)

array('i', [11, 1, 2, 3, 4, 5, 6, 10, 11, 12])


In [32]:
# 6. Add items from list into array using fromlist() method

temp_list = [20,21,22]
my_array.fromlist(temp_list)
print(my_array)

array('i', [11, 1, 2, 3, 4, 5, 6, 10, 11, 12, 20, 21, 22])


In [33]:
# 7. Remove any array element using remove() method

my_array.remove(11) #first occurance of 11 is removed
print(my_array)

array('i', [1, 2, 3, 4, 5, 6, 10, 11, 12, 20, 21, 22])


In [34]:
# 8 . Remove last array element using pop() method

my_array.pop()
print(my_array)

array('i', [1, 2, 3, 4, 5, 6, 10, 11, 12, 20, 21])


In [35]:
# 9. Fetch any element through it's index using index() method

print(my_array.index(12))

8


In [36]:
# 10. Reverse a python array using reverse() method

my_array.reverse()
print(my_array)

array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1])


In [37]:
# 11. Get array buffer information through buffer_info() method

print(my_array.buffer_info())

(140049496301168, 11)


In [38]:
# 12. Check for number of occurences of an element using count() method
my_array.append(12)
print(my_array.count(12))

2


In [41]:
# 13. Convert array to string using tostring() method

strTemp = my_array.tobytes()
print(strTemp)

b'\x15\x00\x00\x00\x14\x00\x00\x00\x0c\x00\x00\x00\x0b\x00\x00\x00\n\x00\x00\x00\x06\x00\x00\x00\x05\x00\x00\x00\x04\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x0c\x00\x00\x00'


In [42]:
ints  = array('i')
ints.frombytes(strTemp)
print(ints)

array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 12])


In [43]:
# 14. Convert array to a python list with same elements using tolist() method

print(my_array.tolist())

[21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 12]


In [46]:
# 15. Append a string to char array using fromstring() method

my_array4 = array('u', ['a','b','c'])
my_string = 'def'
my_array4.fromunicode(my_string)
print(my_array4)

array('u', 'abcdef')


In [47]:
# 16. Slice Element from an array

print(my_array)
print(my_array[1:4])

array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 12])
array('i', [20, 12, 11])


In [48]:
my_array[:4]

array('i', [21, 20, 12, 11])

In [49]:
my_array[2:]

array('i', [12, 11, 10, 6, 5, 4, 3, 2, 1, 12])

In [53]:
my_array[:-1]

array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1])

In [51]:
my_array[:]

array('i', [21, 20, 12, 11, 10, 6, 5, 4, 3, 2, 1, 12])

# Two Dimensional Array

In [54]:
import numpy as np

twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


Insertion - 2D array

In [55]:
# Adding Column
newTwoDArray = np.insert(twoDArray, 0, [[1,2,3,4]], axis=1)
print(newTwoDArray)

[[ 1 11 15 10  6]
 [ 2 10 14 11  5]
 [ 3 12 17 12  8]
 [ 4 15 18 14  9]]


In [56]:
newTwoDArray1 = np.insert(twoDArray, 0,[[1,2,3,4]], axis =0)
print(newTwoDArray1)

[[ 1  2  3  4]
 [11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [57]:
newTwoDArray2 = np.append(twoDArray, [[1,2,3,4]], axis=0)
print(newTwoDArray2)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 1  2  3  4]]


Access an Element of Two Dimensional Array

In [58]:
twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [59]:
def accessElement(array, rowIndex, colIndex):
  if rowIndex >= len(array) and colIndex >= len(array[0]):
    print("Incorrect Index")
  else:
    print(array[rowIndex][colIndex])

accessElement(twoDArray, 1, 2)

11


In [60]:
accessElement(twoDArray, 2, 3)

8


TRaversing 2D Array

In [61]:
def traverseTDArray(array):
  for i in range(len(array)):
    for j in range(len(array[0])):
      print(array[i][j])
traverseTDArray(twoDArray)

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


Search 2D Array

In [62]:
def searchTDArray(array, value):
  for i in range(len(array)):
    for j in range(len(array[0])):
      if array[i][j] == value:
        return 'The value is located at index '+str(i) + ' ' + str(j)
  return 'The element is not found'

searchTDArray(twoDArray, 14)

'The value is located at index 1 1'

Deletion - 2D Array

In [63]:
twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDArray)

newTDArray  = np.delete(twoDArray, 0, axis=0)
print(newTDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [64]:
twoDArray = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(twoDArray)

newTDArray  = np.delete(twoDArray, 0, axis=1)
print(newTDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[15 10  6]
 [14 11  5]
 [17 12  8]
 [18 14  9]]


Time & Space Complexity in 2D Array

| Operation | Time Complexity | Space Complexity |
| --- | --- | --- |
| Creating an empty array | O(1) | O(mn) |
| Inserting a value in an array | O(1)/O(mn) | O(1) |
| Traversing a given array | O(mn) | O(1) |
| Accessing a given cell | O(1) | O(1) |
| Searching a given value | O(mn) | O(1) |
| Deleting a given value | O(1)/O(mn) | O(1) |

When to use Array ?

- To store multiple variables of same data type

- Random access

When to avoid Array?

- same data type elements

- Reserve memory