<a href="https://colab.research.google.com/github/robinkm0610/DSA/blob/main/DSA/05_List.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
int = [1,2,3,4]

In [ ]:
mixtype = [1,2,"a", [1,2,3]]
mixtype

[1, 2, 'a', [1, 2, 3]]

Accessing/Traversing the list

In [ ]:
shoppingList = ['Milk', 'Cheese', 'Butter']
shoppingList

['Milk', 'Cheese', 'Butter']

In [ ]:
shoppingList[0]

'Milk'

In [ ]:
shoppingList[2]

'Butter'

In [ ]:
shoppingList[3]

IndexError: list index out of range

In [ ]:
print('Bread' in shoppingList)

False


In [ ]:
print('Butter' in shoppingList)

True


In [ ]:
print(shoppingList[-1])

Butter


In [ ]:
# Traverse

for i in shoppingList:
  print(i)

Milk
Cheese
Butter


In [ ]:
for i in range(len(shoppingList)):
  print(shoppingList[i])

Milk
Cheese
Butter


In [ ]:
for i in range(len(shoppingList)):
  shoppingList[i] = shoppingList[i] + '+'
  print(shoppingList[i])

Milk+
Cheese+
Butter+


Update/Insert - List

In [ ]:
myList = [1,2,3,4,5,6,7]
myList

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
myList[2] = 33
myList

[1, 2, 33, 4, 5, 6, 7]

In [ ]:
myList[4] = 55
myList

[1, 2, 33, 4, 55, 6, 7]

Insert

- insert()
- append()
- extend()


In [ ]:
myList = [1,2,3,4,5,6,7]
myList

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
myList.insert(2, 22)
myList

[1, 2, 22, 3, 4, 5, 6, 7]

In [ ]:
myList.append(88)
myList

[1, 2, 22, 3, 4, 5, 6, 7, 88]

In [ ]:
newList = [11,12,13,14]
myList.extend(newList)
myList

[1, 2, 22, 3, 4, 5, 6, 7, 88, 11, 12, 13, 14]

Slice Delete in List

In [ ]:
myList = ['a', 'b', 'c', 'd', 'e', 'f']
myList[0:2]

['a', 'b']

In [ ]:
myList[1:]

['b', 'c', 'd', 'e', 'f']

In [ ]:
myList[:]

['a', 'b', 'c', 'd', 'e', 'f']

In [ ]:
myList[0:2] = ['x', 'y']
myList

['x', 'y', 'c', 'd', 'e', 'f']

In [ ]:
#Pop() Method

myList.pop()
myList

['x', 'y', 'c', 'd', 'e']

In [ ]:
myList.pop(1)
myList

['x', 'c', 'd', 'e']

In [ ]:
print(myList.pop(2)) #POp returns the deleted element

d


In [ ]:
#delete () method

del myList[1]
myList

['x', 'e']

In [ ]:
myList = ['a', 'b', 'c', 'd', 'e', 'f']
del myList[0:2]
myList

['c', 'd', 'e', 'f']

In [ ]:
myList = ['a', 'b', 'c', 'd', 'e', 'f']
myList.remove('b')
myList

['a', 'c', 'd', 'e', 'f']

List Operations

In [ ]:
a = [1,2,3]
b = [4,5,6]
c = a + b
c

[1, 2, 3, 4, 5, 6]

In [ ]:
a = [0,1]
a = a * 4
a

[0, 1, 0, 1, 0, 1, 0, 1]

In [ ]:
a = [1,2,3,4,5,6]
print(len(a))

6


In [ ]:
max(a)

6

In [ ]:
min(a)

1

In [ ]:
sum(a)

21

In [ ]:
sum(a)/len(a)

3.5

In [ ]:
myList = list()
while (True):
  inp = input('Enter a number: ')
  if inp == 'done': break
  value = float(inp)
  myList.append(value)

average = sum(myList) / len(myList)
print('Average: ', average)


Enter a number: 5
Enter a number: 9
Enter a number: 78
Enter a number: 854
Enter a number: done
Average:  236.5


Lists & Strings

In [ ]:
a = 'spam'
b = list(a)
b

['s', 'p', 'a', 'm']

In [ ]:
a = 'spam spam spam'
b = list(a)
b

['s', 'p', 'a', 'm', ' ', 's', 'p', 'a', 'm', ' ', 's', 'p', 'a', 'm']

In [ ]:
a = 'spam spam spam'
b = a.split()
b

['spam', 'spam', 'spam']

In [ ]:
a = 'spam-spam1-spam2'
b = a.split('-')
b

['spam', 'spam1', 'spam2']

In [ ]:
'-'.join(b)

'spam-spam1-spam2'

Common List pitfalls

In [ ]:
myList = [78,8,1,58, 2,3,4]
myList.sort()
myList

[1, 2, 3, 4, 8, 58, 78]

| Stretch/Untouched | ProbDistribution | Accuracy |
| --- | --- | --- |
|Creating a List | O(1) | O(n)|
|Inserting a value in a LIst | O(1)/O(n) | O(1)|
|Traversing a given List | O(n) | O(1) |
|Accessing a given List | O(1) | O(1) |
|Searching a given value | O(n) | O(1) |
|Deleting a given value | O(1)/O(n) | O(n) |

Project Array Lists

In [4]:
#Calculate Average Temperature
numDays = int(input("How many day's temperature?"))
total = 0
temp = []
for i in range(numDays):
  nextDay = int(input("Day" + str(i+1) + "'s high temp: "))
  temp.append(nextDay)
  total += nextDay

avg = round(total / numDays,2)
print("\nAverage = " + str(avg))

above = 0
for i in temp:
  if i > avg:
    above += 1

print(str(above) + " days(s) above average")

How many day's temperature?5
Day1's high temp: 20
Day2's high temp: 25
Day3's high temp: 39
Day4's high temp: 18
Day5's high temp: 12

Average = 22.8
2 days(s) above average


Interview Questions

Q1. How to find the missing number in an integer array of 1 to 100 ?

In [6]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]

def findMissing(list, n):
  sum1 = 100 * (100 + 1) /2
  sum2 = sum(list)
  return sum1 - sum2

print(int(findMissing(mylist, 100)))

73


Q2. Write a program to find all pairs of integers whose sum is equal to a given number.

In [9]:
def findpairs(lst, sum):
  for i in range(len(lst)):
    for j in range(i+1, len(lst)):
      if lst[i] == lst[j]:
        continue
      elif lst[i] + lst[j] == sum:
        print(lst[i], lst[j])

mylist =  [1,2,3,2,3,4,5,6]
findpairs(mylist, 6)

1 5
2 4
2 4


Q3. How to check if an array contains a number in python

In [10]:
import numpy as np
myArray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

def findNumber(array,num):
  for i in range(len(array)):
    if array[i] == num:
      return True
  return False

print(findNumber(myArray, 10))

True


Q4. How to find maximum product of two integers in the array where all elements are positive ?

In [16]:
import numpy as np
myArray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])


def maxProduct(array):
  maxProduct = 0
  for i in range(len(array)):
    for j in range(i+1, len(array)):
      if array[i] * array[j]  > maxProduct:
        maxProduct = array[i] * array[j]
        pairs = str(array[i]) + ", " + str(array[j])
  print(pairs)
  print(maxProduct)

maxProduct(myArray)


19, 20
380


Q5. Is Unique

In [17]:
def isUnique(lst):
  a = []
  for i in lst:
    if i in a:
      return False
    else:
      a.append(i)
  return True

mylist =  [1,2,3,2,3,4,5,6]
print(isUnique(mylist))

False


In [18]:
myList = [1, 2, 3, 4, 5]
print(isUnique(myList))

True


Q6. Permutation

In [19]:
def permutation(list1, list2):
  if len(list1) != len(list2):
    return False
  list1.sort()
  list2.sort()
  if list1 == list2:
    return True
  else:
    return False

list1 = [1, 2, 3, 4, 5]
list2 = [5, 4, 3, 2, 1]
print(permutation(list1, list2))

True


Q7. Rotate Matrix - Given an image represented by a N*N matrix write a method to rotate the image by 90 degress.

In [22]:
import numpy as np

myArray = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(myArray)
def rotate(matrix):
  n = len(matrix)
  print(f"n = {n}")
  for layer in range(n //2):
    first = layer
    print(f"first = {first}")
    last = n - layer -1
    print(f"last = {last}")
    for i in range(first, last):
            # save top
            top = matrix[layer][i]
            print(f"top = {top}")
            # left -> top
            matrix[layer][i] = matrix[-i - 1][layer]
            print(f"matrix[layer][i] = {matrix[layer][i]}")
            # bottom -> left
            matrix[-i - 1][layer] = matrix[-layer - 1][-i - 1]
            print(f"matrix[-i - 1][layer] = {matrix[-i - 1][layer]}")
            # right -> bottom
            matrix[-layer - 1][-i - 1] = matrix[i][- layer - 1]
            print(f"matrix[-layer - 1][-i - 1] = {matrix[-layer - 1][-i - 1]}")
            # top -> right
            matrix[i][- layer - 1] = top
            print(f"matrix[i][- layer - 1] = {matrix[i][- layer - 1]}")
  return matrix

print(rotate(myArray))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
n = 3
first = 0
last = 2
top = 1
matrix[layer][i] = 7
matrix[-i - 1][layer] = 9
matrix[-layer - 1][-i - 1] = 3
matrix[i][- layer - 1] = 1
top = 2
matrix[layer][i] = 4
matrix[-i - 1][layer] = 8
matrix[-layer - 1][-i - 1] = 6
matrix[i][- layer - 1] = 2
[[7 4 1]
 [8 5 2]
 [9 6 3]]
